name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - run: sudo docker build . --file Dockerfile --tag show-me-recipes:latest 
    - run: sudo docker stop show-me-recipes
    - run: sudo docker rm show-me-recipes
    - run: sudo docker run -d --name show-me-recipes -p 80:80 show-me-recipes:latest
